---

version: '3.2'

services:
  server:
    image: uip9av6y/nsd
    ports:
      - "${DNS_PORT:-53}:53"
      - "${DNS_PORT:-53}:53/udp"
    volumes:
      - type: volume
        source: server-config
        target: /etc/nsd/conf.d
        read_only: true
      - type: volume
        source: server-zones
        target: /etc/nsd/zones.d
        read_only: true
      - type: volume
        source: server-data
        target: /var/db/nsd
    deploy:
      replicas: 1
  config:
    image: uip9av6y/confgit
    working_dir: /data
    environment:
      CONFGIT_URL: "${CONFIG_REPO:?missing config repo URL}"
      CONFGIT_BRANCH: "${CONFIG_BRANCH:-master}"
      CONFGIT_USERNAME: "${GIT_USER:-git}"
      CONFGIT_IDENTITY_SECRET: config_reader_key
    volumes:
      - type: volume
        source: server-config
        target: /data
    secrets:
      - config_reader_key
    deploy:
      replicas: 1
      restart_policy:
        condition: none
  zones:
    image: uip9av6y/confgit
    working_dir: /data
    environment:
      CONFGIT_URL: "${ZONES_REPO:?missing zones repo URL}"
      CONFGIT_BRANCH: "${ZONES_BRANCH:-master}"
      CONFGIT_USERNAME: "${GIT_USER:-git}"
      CONFGIT_IDENTITY_SECRET: config_reader_key
    volumes:
      - type: volume
        source: server-zones
        target: /data
    secrets:
      - config_reader_key
    deploy:
      replicas: 1
      restart_policy:
        condition: none

volumes:
  server-data:
  server-zones:
  server-config:

secrets:
  config_reader_key:
    external:
      name: "${GIT_KEY:-git_reader_key}"
