---

version: '3.2'

services:
  monitor:
    image: v2tec/watchtower
    command:
      - --cleanup
      - --schedule "${CRON_SCHEDULE}"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: any
