---

version: '3.2'

services:
  webapp:
    image: uip9av6y/unifi-controller
    ports:
      - "8080:8080"
      - "8880:8880"
      - "8443:8443"
      - "8843:8843"
      - "3478:3478/udp"
      - "6789:6789"
    environment:
      SYSTEM_IP: "$SYSTEM_IP"
    volumes:
      - type: volume
        source: webapp-backups
        target: /usr/lib/unifi/data/backup/autobackup
    networks:
      backend:
        aliases:
         - controller
    deploy:
      replicas: 1
  persistence:
    image: mongo
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    networks:
      backend:
        aliases:
         - mongo
    deploy:
      replicas: 1

volumes:
  webapp-backups:
  mongo-data:

networks:
  backend:
